language: node_js
node_js:
  - "12"
  - "13"
cache:
  directories:
    - "node_modules"
env:
  global:
    - CC_TEST_REPORTER_ID=3b796dff159e18c68c3ca8e0784349e55e7b52212b010515af875eef9b353c50
    - MYSQL_HOST=localhost MYSQL_DATABASE=test MYSQL_USER=root MYSQL_PASSWORD=""
before_install:
  - npm i -g npm@latest
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - mysql -e 'CREATE DATABASE test;'
install:
  - npm install
  - npm install @rxstack/core@^0.6 @rxstack/platform@^0.6 @rxstack/exceptions@^0.5 @rxstack/query-filter@^0.5 @rxstack/security@^0.6 @rxstack/async-event-dispatcher@^0.5 @rxstack/service-registry@^0.5 winston@^3.2.1
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
services:
  - mysql
