language: node_js
node_js:
  - "9"
  - "10"
  - "11"
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
    repo_token:

before_install:
  - npm i -g npm@latest
  - mysql -e 'CREATE DATABASE test;'
install:
  - npm install
  - npm install @rxstack/core@^0.1 @rxstack/data-fixtures@^0.1 @rxstack/platform@^0.1 @rxstack/exceptions@^0.1 @rxstack/query-filter@^0.1 injection-js@^2.1 reflect-metadata@^0.1
script:
  - npm test
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info

services:
  - mysql

env:
  - MYSQL_HOST=localhost
  - MYSQL_DATABASE=test
  - MYSQL_USER=root
  - MYSQL_PASSWORD=""